import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
  boxProvider: {
    position: 'absolute',
    width: '218px',
    height: '71px',
    left: '23px',
    top: '53px',
    backgroundColor: '#355072',
  },
  MainBox: {
    '&.active': {
      background: 'black',
    },
    '&:hover': {
      backgroundColor: '#E9F4F5',
    },
    display: 'flex',
    width: '216px',
    height: '48px',
    flexDirection: 'row',
    alignItems: 'center',
    p: '12px',
    gap: '12px',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  TypographyBox: {
    '&:hover': {
      color: '#4CA7A8',
    },
    width: '80%',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '130%',
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
  TypographyBoxOnly: {
    marginLeft: '-7px',
    marginBottom: '10px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#AEAEAE',
  },
  TypographyBoxActive: {
    width: '80%',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#4CA7A8',
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
  formFieldStyle: {
    margin: "10px 0 10px 0",
    padding: "15px",
    fontSize: "16px",
    border: 0,
    fontFamily: "'Roboto', sans-serif",
    borderRadius: ".25rem",
  },
  spanStyle: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: "14px",
    color: "red",
    marginBottom: "15px",
  },
  formFieldStyleButton: {
    "&:disabled": {
      opacity: 0.1
    },
    margin: "10px 0 10px 0",
    padding: "15px",
    fontSize: "16px",
    border: 0,
    fontFamily: "'Roboto', sans-serif",
    borderRadius: ".25rem",
    background: "#ff8400",
    color: "#131313",
    fontWeight: 500,
    cursor: "pointer",
    borderRadius: ".25rem",
  },
  TypographyHeader: {
    width: "86px",
    height: "34px",
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "140%",
    color: "#0F1527",
    flex: "none",
    order: 0,
    flexGrow: 0,
  },
  TypographyText: {
    width: "229px",
    height: "21px",
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "130%",
    color: "#AEAEAE",
    flex: "none",
    order: 1,
    flexGrow: 0,
  },
  BoxButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 24px",
    gap: "8px",
    width: "144px",
    height: "38px",
    background: "#4CA7A8",
    borderRadius: "6px",
    flex: "none",
    order: 0,
    flexGrow: 0,
    marginTop: "10px",
  },
  ButtonAdd: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    padding: "10px 24px",
    alignItems: "center",
    width: "144px",
    height: "38px",
    background: "#4CA7A8",
    borderRadius: "6px",
    flex: "none",
    order: 0,
    flexGrow: 0,
    border: 0,
    cursor: "pointer",
  },
  BoxSearch: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    padding: "16px",
    gap: "8px",
    width: "460px",
    height: "56px",
    background: "#FAFAFA",
    borderRadius: "12px",
    flex: "none",
    flexGrow: 0,
    margin: "0px 10px",
  },
});
