import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
  boxProvider: {
    position: 'absolute',
    width: '218px',
    height: '71px',
    left: '23px',
    top: '53px',
    backgroundColor: '#355072',
  },
  MainBox: {
    '&.active': {
      background: 'black',
    },
    '&:hover': {
      backgroundColor: '#E9F4F5',
    },
    display: 'flex',
    width: '216px',
    height: '48px',
    flexDirection: 'row',
    alignItems: 'center',
    p: '12px',
    gap: '12px',
    borderRadius: '6px',
    flex: 'none',
    order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  TypographyBox: {
    '&:hover': {
      color: '#4CA7A8',
    },
    width: '80%',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '130%',
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
  TypographyBoxOnly: {
    marginLeft: '-7px',
    marginBottom: '10px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#AEAEAE',
  },
  TypographyBoxActive: {
    width: '80%',
    height: '21px',
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '130%',
    color: '#4CA7A8',
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
});
